# Configuração do GitHub Pages
title: "MaisEsports YouTube Tracker"
description: "Extensão experimental para Chrome que monitora novos vídeos do canal MaisEsports"
url: "https://gor0d.github.io"
baseurl: "/mais-esports-yt-tracker"

# Autor
author:
  name: "Gor0d"
  github: "Gor0d"

# Tema
remote_theme: pages-themes/hacker@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configurações do site
markdown: kramdown
highlighter: rouge
permalink: pretty

# Configurações de build
safe: true
incremental: false

# Excluir arquivos do build
exclude:
  - manifest.json
  - background.js
  - popup.html
  - popup.js
  - content.js
  - maisesports.png
  - icons/
  - .gitignore
  - node_modules/
  - vendor/

# SEO
lang: pt-BR

# Configurações específicas do projeto
project:
  name: "MaisEsports YouTube Tracker"
  version: "1.0.0"
  chrome_extension: true
  experimental: true