# Configuração do GitHub Pages
title: "MaisEsports YouTube Tracker"
description: "Extensão experimental para Chrome que monitora novos vídeos do canal MaisEsports"
url: "https://gor0d.github.io"
baseurl: "/mais-esports-yt-tracker"

# Autor
author:
  name: "Gor0d"
  email: "emersongsguimaraes@gmail.com"
  github: "Gor0d"

# Tema
theme: minima
remote_theme: pages-themes/hacker@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configurações do site
markdown: kramdown
highlighter: rouge
permalink: pretty

# Configurações de build
safe: true
incremental: false
profile: false

# Excluir arquivos do build
exclude:
  - manifest.json
  - background.js
  - popup.html
  - popup.js
  - content.js
  - maisesports.png
  - icons/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Configurações sociais
github_username: Gor0d
social_links:
  - https://github.com/Gor0d/mais-esports-yt-tracker

# Google Analytics (opcional)
# google_analytics: UA-XXXXXXXXX-X

# SEO
lang: pt-BR
favicon: /assets/favicon.ico

# Configurações específicas do projeto
project:
  name: "MaisEsports YouTube Tracker"
  version: "1.0.0"
  chrome_extension: true
  experimental: true